name: Keep Alive
on:
  schedule:
    - cron: "0 0 */10 * *"

jobs:
  cronjob-based-github-action:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
