name: Keep Alive
on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  keepalive-job:
    name: Keep Alive
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
