name: Keep Alive
on:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  keepalive-job:
    name: Keep Alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
